migrated execute logic to executor; enhanced coverage script

diff --git a/.scripts/test b/.scripts/test
--- a/.scripts/test
+++ b/.scripts/test
@@ -1,15 +1,53 @@
-#!/bin/bash
-set -eu
+#!/bin/sh
+# Generate test coverage statistics for Go packages.
+#
+# Works around the fact that `go test -coverprofile` currently does not work
+# with multiple packages, see https://code.google.com/p/go/issues/detail?id=6909
+#
+# Usage: script/coverage [--html|--coveralls]
+#
+#     --html      Additionally create HTML report and open it in browser
+#     --coveralls Push coverage statistics to coveralls.io
+#
+# Source: https://github.com/mlafeldt/chef-runner/blob/v0.7.0/script/coverage
 
-BOLD=$(tput bold)
-NORMAL=$(tput sgr0)
+set -e
 
-echo "${BOLD}Testing${NORMAL}"
+workdir=.cover
+profile="$workdir/cover.out"
+mode=count
 
-cd $(dirname $0)/..
+generate_cover_data() {
+    rm -rf "$workdir"
+    mkdir "$workdir"
 
-PACKAGES=". $(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"
+    for pkg in "$@"; do
+        f="$workdir/$(echo $pkg | tr / -).cover"
+        go test -covermode="$mode" -coverprofile="$f" "$pkg"
+    done
 
-[ $(arch) == "x86_64" ] && RACE=-race
-#go test ${RACE} -cover -tags=test ${PACKAGES}
-go test -cover -tags=test ${PACKAGES}
+    echo "mode: $mode" >"$profile"
+    grep -h -v "^mode:" "$workdir"/*.cover >>"$profile"
+}
+
+show_cover_report() {
+    go tool cover -${1}="$profile"
+}
+
+push_to_coveralls() {
+    echo "Pushing coverage statistics to coveralls.io"
+    goveralls -coverprofile="$profile"
+}
+
+generate_cover_data $(go list ./...)
+show_cover_report func
+case "$1" in
+"")
+    ;;
+--html)
+    show_cover_report html ;;
+--coveralls)
+    push_to_coveralls ;;
+*)
+    echo >&2 "error: invalid option: $1"; exit 1 ;;
+esac
